### ISSUE TITLE
login issue/registration issue

### ISSUE THREAD

**Issue by JaySrivastav007** [Ankit-Khachane/CollegeSystem#2]
everything is loaded and build successfully but when i login or register the app terminates..... and please also let me know where is the data base for data storage or some other data storing method is used

**Comment by azharpatel4** [comment]
even im getting the same issue and what about the database which database u have used

**Comment by azharpatel4** [comment]
> everything is loaded and build successfully but when i login or register the app terminates..... and please also let me know where is the data base for data storage or some other data storing method is used

is ur app working login and register

**Comment by Ankit-Khachane** [comment]
Hello everyone one

I noticed the issue about crashing that's happening due to the my cloud Server ,i haven't renewed it that's why the api for the  same doesn't work and keeps crashing the app, and all the data are stored on cloud server database so  that's also handled by api the project is  not actively maintained if you guys want to you can start of studying the api for cloud server called **Parse MBaaS** its currently is provided by back4app

**Comment by azharpatel4** [comment]
can you provide how to add cloud server i.e back4app
